FROM us.gcr.io/pbm-mac-lp-prod-ai/pbm_base:LP_Model_Improvements_GCP-9bc4aa3-WIP-0
RUN ["pip", "install", "PuLP==2.4", "XlsxWriter==1.3.7", "--index-url", "https://nexus-ha.cvshealth.com:9443/repository/pypi-proxy/simple"]
