FROM python:3.8-slim-buster
# copy local scripts over
ENV PYTHONPATH=PYTHONPATH:/
COPY ./GER_LP_Code .
RUN ["mkdir", "-p", "/opt/gurobi"]
COPY ./gurobi.lic /opt/gurobi/ 
RUN rm -f CPMO_parameters.py  # (remove so old copy doesn't cause issues with future runs)
# create directory structure
RUN mkdir -p Dynamic_Input Logs LP Output
# install python dependencies
RUN ["pip", "install", "--upgrade", "fsspec==0.8.4", "gcsfs==0.7.1", "google-cloud-bigquery==3.4.0", "google-auth-oauthlib==0.5.3",\
    "google-cloud-bigquery-storage==2.13.2", "google-cloud-storage==1.30.0", "pyarrow==8.0.0", \
    "numpy==1.18.5", "pandas==1.1.4", "xlrd==1.2.0", "duckdb==0.8.0", "grpcio==1.47.0", "MarkupSafe==1.1.1", \
    "db-dtypes==1.0.4", "numba", "duckdb==0.8.0", "gurobipy==10.0.3", "--index-url", "https://nexus-ha.cvshealth.com:9443/repository/pypi-proxy/simple"]